spring.application.name=heathos

spring.datasource.driver-class-name=org.postgresql.Driver

# application.properties  (base — reads from env variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


jwt.secret=thisismysecretkeyforhmssystempleasechangethisinproduction2025
jwt.expiration-ms=86400000

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true


